name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [2.7.2, 3.0.0]

    steps:
      - uses: actions/checkout@v2

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install bundler
        run: gem install bundler

      - name: Install gems
        run: |
          bundle config set --local without benchmark
          bundle install --jobs=3

      - name: Tests
        run: COVERAGE=true bundle exec rspec

      - name: Upload coverage results
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: coverage-report
          path: coverage
