name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    name: RSpec
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7' # Version range or exact version of a Ruby version to use, using semvers version range syntax.
      - run: |
          gem install bundler
          bundle install
          bundle exec rspec
